In [2]:
import pandas as pd
import statsmodels.api as sm

In [9]:
train = 'D:/estrategia_/train.csv'

df = pd.read_csv(train)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [19]:
y = 'SalePrice'
columns = ['MSSubClass', 'LotFrontage', 'LotArea', 'YrSold', 'SalePrice']
df = df[columns]
df = df.dropna()
df

      MSSubClass  LotFrontage  LotArea  YrSold  SalePrice
0             60         65.0     8450    2008     208500
1             20         80.0     9600    2007     181500
2             60         68.0    11250    2008     223500
3             70         60.0     9550    2006     140000
4             60         84.0    14260    2008     250000
...          ...          ...      ...     ...        ...
1455          60         62.0     7917    2007     175000
1456          20         85.0    13175    2010     210000
1457          70         66.0     9042    2010     266500
1458          20         68.0     9717    2010     142125
1459          20         75.0     9937    2008     147500

[1201 rows x 5 columns]

In [20]:
X = df.drop([y], axis=1)

In [12]:
from sklearn.preprocessing import StandardScaler

In [21]:
scaler = StandardScaler()
normalized_x = scaler.fit_transform(X)
normalized_x = pd.DataFrame(normalized_x, columns=X.columns)

In [26]:
modelo = sm.OLS(df[y].values, normalized_x)

In [30]:
res = modelo.fit()

In [31]:
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.028
Model:                            OLS   Adj. R-squared (uncentered):              0.025
Method:                 Least Squares   F-statistic:                              8.544
Date:                Tue, 29 Nov 2022   Prob (F-statistic):                    8.48e-07
Time:                        08:02:44   Log-Likelihood:                         -16341.
No. Observations:                1201   AIC:                                  3.269e+04
Df Residuals:                    1197   BIC:                                  3.271e+04
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
MSSubClass   4291.6977   6156.920      0.697      0.486   -7787.858    1.64e+04
LotFrontage  2.391e+04   6666.429      3.587      0.000    1.08e+04     3.7e+04
LotArea      1.662e+04   6277.661      2.647      0.008    4300.074    2.89e+04
YrSold      -1706.2669   5674.041     -0.301      0.764   -1.28e+04    9425.906
==============================================================================
Omnibus:                      402.830   Durbin-Watson:                   0.304
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2037.389
Skew:                           1.478   Prob(JB):                         0.00
Kurtosis:                       8.654   Cond. No.                         1.81
==============================================================================

Notes:
[1] RÂ² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""